<a href="https://colab.research.google.com/github/pooja7490/Softcomputing-Practical-Exam-2020/blob/main/practical_code.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# MP Neuron for Logic Gates (AND,OR,AND-NOT)

In [ ]:
#AND

import numpy as np
x=np.array([[1,1],[1,0],[0,1],[0,0]])
t=np.array([[1],[0],[0],[0]])
w=np.array([[0],[0]])
theta=1
yin=np.zeros(shape=(4,1))
y=np.zeros(shape=(4,1))
yin=np.dot(x,w)
i=0
found=0
while(found==0):
        i=0
        yin=np.dot(x,w)
    	#print(yin)
        while(i<4):
            if yin[i]>=theta:
                y[i]=1
                i=i+1
            else:
            	y[i]=0
            	i=i+1
    
        if (y==t).all():
        	print("MODEL IS TRAINED ")
        	print("\nOutput : \n",y)
        	print("\nweights : ",w,"\n")
        	print("theta : ",theta)
        	found=1
        else:
       	    print("MODEL IS NOT TRAINED")
            w=np.zeros(shape=(0,0))
            theta=int(input("Enter New Theta : "))
            for k in range(int(2)):
            	w1=int(input("Enter Weight : "))
            	w=np.append(w,w1)





MODEL IS NOT TRAINED
Enter New Theta : 2
Enter Weight : 1
Enter Weight : 1
MODEL IS TRAINED 

Output : 
 [[1.]
 [0.]
 [0.]
 [0.]]

weights :  [1. 1.] 

theta :  2


In [ ]:
#OR

import numpy as np
x=np.array([[1,1],[1,0],[0,1],[0,0]])
t=np.array([[1],[1],[1],[0]])
w=np.array([[0],[0]])
theta=1
yin=np.zeros(shape=(4,1))
y=np.zeros(shape=(4,1))
yin=np.dot(x,w)
i=0
found=0
while(found==0):
    i=0
    yin=np.dot(x,w)
    while(i<4):
        if yin[i]>=theta:
            y[i]=1
            i=i+1
        else:
            y[i]=0
            i=i+1
    #print("y",y)
    #print("t",t)
    if(y==t).all():
        print("MODEL IS TRAINED ")
        print("\nOutput : \n",y)
        print("\nweights : ",w,"\n")
        print("theta : ",theta)
        found=1
    else:
       	print("MODEL IS NOT TRAINED")
        w=np.zeros(shape=(0,0))
        theta=int(input("Enter New Theta : "))
        for k in range(int(2)):
            w1=int(input("Enter Weight : "))
            w=np.append(w,w1)




MODEL IS NOT TRAINED
Enter New Theta : 1
Enter Weight : 1
Enter Weight : 1
MODEL IS TRAINED 

Output : 
 [[1.]
 [1.]
 [1.]
 [0.]]

weights :  [1. 1.] 

theta :  1


In [ ]:
#NAND
import numpy as np
x=np.array([[1,1],[1,0],[0,1],[0,0]])
t=np.array([[0],[1],[0],[0]])
w=np.array([[0],[0]])
theta=1
yin=np.zeros(shape=(4,1))
y=np.zeros(shape=(4,1))
yin=np.dot(x,w)
i=0
found=0
while(found==0):
    i=0
    yin=np.dot(x,w)
    	#print(yin)
    while(i<4):
        if yin[i]>=theta:
            y[i]=1
            i=i+1
       	else:
            y[i]=0
            i=i+1
    #print("y",y)
    #print("t",t)
    if (y==t).all():
        print("MODEL IS TRAINED ")
        print("\nOutput : \n",y)
        print("\nweights : ",w,"\n")
        print("theta : ",theta)
        found=1
    else:  
        print("MODEL IS NOT TRAINED")
        w=np.zeros(shape=(0,0))
        theta=int(input("Enter New Theta : "))
        for k in range(int(2)):
            w1=int(input("Enter Weight : "))
            w=np.append(w,w1)



MODEL IS NOT TRAINED
Enter New Theta : 1
Enter Weight : 1
Enter Weight : -1
MODEL IS TRAINED 

Output : 
 [[0.]
 [1.]
 [0.]
 [0.]]

weights :  [ 1. -1.] 

theta :  1


In [2]:
#NOT

import numpy as np
x=np.array([[0],[1]])
t=np.array([[1],[0]])
w=np.array([0])
theta=1
yin=np.zeros(shape=(2,1))
y=np.zeros(shape=(2,1))
yin=np.dot(x,w)
i=0
found=0
while(found==0):
    i=0
    yin=np.dot(x,w)
    print(yin)
    while(i<2):
        if yin[i]>=theta:
            y[i]=1 
            i=i+1
            
            	#if(i==4):
                	#break
        else:
            y[i]=0
            i=i+1
    print("y",y)
    print("t",t)
    if (y==t).all():
        print("MODEL IS TRAINED ")
        print("\nOutput : \n",y)
        print("\nweights : ",w,"\n")
        print("theta : ",theta)
        found=1
    else:
        print("MODEL IS NOT TRAINED")
        w=np.zeros(shape=(0,0))
        theta=int(input("Enter New Theta : "))
        for k in range(int(1)):
            w=int(input("Enter Weight : "))



[0 0]
y [[0.]
 [0.]]
t [[1]
 [0]]
MODEL IS NOT TRAINED
Enter New Theta : 2
Enter Weight : 1
[[0]
 [1]]
y [[0.]
 [0.]]
t [[1]
 [0]]
MODEL IS NOT TRAINED
Enter New Theta : 1
Enter Weight : 1
[[0]
 [1]]
y [[0.]
 [1.]]
t [[1]
 [0]]
MODEL IS NOT TRAINED
Enter New Theta : -1
Enter Weight : 1
[[0]
 [1]]
y [[1.]
 [1.]]
t [[1]
 [0]]
MODEL IS NOT TRAINED
Enter New Theta : 1
Enter Weight : -1
[[ 0]
 [-1]]
y [[0.]
 [0.]]
t [[1]
 [0]]
MODEL IS NOT TRAINED
Enter New Theta : 0
Enter Weight : -1
[[ 0]
 [-1]]
y [[1.]
 [0.]]
t [[1]
 [0]]
MODEL IS TRAINED 

Output : 
 [[1.]
 [0.]]

weights :  -1 

theta :  0
